web:
  image: nginx
  volumes:
    - ./build:/usr/share/nginx/html
    - ./default.conf:/etc/nginx/conf.d/mysite.template
  ports:
    - "${CDN_CHECK_SITE_PORT}:80"
  environment:
    - NGINX_PORT=80
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

